export default `<?php

/**
 * Generated by the WordPress Meta Box Generator By John Tendik
 * https://johntendik.com/tools/wordpress-meta-box-generator/
 * 
 * Retrieving the values:
 * test = get_post_meta( get_the_ID(), 'name_of_field', true )
 */

class JT_Metabox_Generator {
  public function __construct() {
		add_action( 'add_meta_boxes', array( $this, 'add_meta_boxes' ) );
		add_action( 'save_post', array( $this, 'save_post' ) );
	}

  public function add_meta_boxes() {
    add_meta_box(
      '@@metabox-id@@',
      __('@@metabox-title@@', '@@text-domain@@'),
      array( $this, 'add_meta_box_callback' ),
      array(@@screens@@),
      '@@context@@',
      '@@priority@@'
    );
	}

  public function save_post() {
    @@save_post@@
  }

  public function add_meta_box_callback() {
    echo "<style>div.jt-meta-box-flex{display:flex;align-items:flex-start;margin: 14px 0;}div.jt-meta-box-flex label{width: 190px;margin: 0}</style>";
    @@fields@@
  }
}

new JT_Metabox_Generator;

?>`;